repos:
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    name: Black format python files
    language_version: python3 # Should be a command that runs python3.6+
    entry: black

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2  # pick a git hash / tag to point to
  hooks:
  - id: flake8
    additional_dependencies:
    - pyproject-flake8
    - flake8-deprecated
    - flake8-debugger
    - flake8-bugbear
    - flake8-super
    - flake8-tidy-imports
    exclude: "(rossweb/integrations/__template__|py_proto_classes)"
    language_version: python3
    entry: pflake8

- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort
    entry: isort
    language_version: python3

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.941'  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
