image: python:3.6.3
pipelines:
  default:
    - step:
        script:
          - pip install tox detox
          - detox
        services:
          - database
definitions:
  services:
    database:
      image: postgres
      environment:
        POSTGRES_DB: 'occupation'
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'